// ── Images (di public/assets, akses via URL string langsung) ──────────────
export const DataImage = {
  HeroImage: "/assets/conixx.jpg",
};

export const listTools = [
  { id: 1,  gambar: "/assets/tools/vscode.png",    nama: "Visual Studio Code", ket: "Code Editor",         dad: "100"  },
  { id: 2,  gambar: "/assets/tools/reactjs.png",   nama: "React JS",           ket: "Framework",           dad: "200"  },
  { id: 3,  gambar: "/assets/tools/flutter.png",   nama: "Flutter",            ket: "Framework",           dad: "300"  },
  { id: 4,  gambar: "/assets/tools/tailwind.png",  nama: "Tailwind CSS",       ket: "Framework",           dad: "400"  },
  { id: 5,  gambar: "/assets/tools/bootstrap.png", nama: "Bootstrap",          ket: "Framework",           dad: "500"  },
  { id: 6,  gambar: "/assets/tools/js.png",        nama: "Javascript",         ket: "Language",            dad: "600"  },
  { id: 7,  gambar: "/assets/tools/nodejs.png",    nama: "Node JS",            ket: "Javascript Runtime",  dad: "700"  },
  { id: 8,  gambar: "/assets/tools/github.png",    nama: "Github",             ket: "Repository",          dad: "800"  },
  { id: 9,  gambar: "/assets/tools/android.png",   nama: "Android Studio",     ket: "Emulator",            dad: "900"  },
  { id: 10, gambar: "/assets/tools/canva.png",     nama: "Canva",              ket: "Design App",          dad: "1000" },
  { id: 11, gambar: "/assets/tools/figma.png",     nama: "Figma",              ket: "Design App",          dad: "1100" },
  { id: 12, gambar: "/assets/tools/mysql.png",     nama: "MySQL",              ket: "Database",            dad: "1100" },
];

export const listProyek = [
  {
    id: 1,
    gambar: "/assets/proyek/proyek1.png",
    nama: "Aplikasi Hotel Bengkalis",
    desk: "Aplikasi yang berfungsi mencari Hotel dan Wisma terdekat dari posisi pengguna",
    tools: ["Dart", "Google Maps", "Google Street View"],
    dad: "200",
    link: "https://github.com/solihunsir/pencarian-hotel-bengkalis-dengan-Astar",
  },
  {
    id: 2,
    gambar: "/assets/proyek/proyek2.png",
    nama: "Judi Guard",
    desk: "Website untuk mencegah dan memberantas Komentar Judi Online di Platform Youtube ",
    tools: ["React.js", "Express", "Node.js", "TailwindCSS"],
    dad: "300",
    link: "https://github.com/solihunsir/Judi-Guard",
  },
  {
    id: 3,
    gambar: "/assets/proyek/proyek3.png",
    nama: "Portal Berita",
    desk: "Website Portal Berita yang memberikan berita yang terbaru dan relevan ",
    tools: ["Laravel", "TailwindCSS"],
    dad: "400",
    link: "https://github.com/solihunsir/portal_berita",
  },
  {
    id: 4,
    gambar: "/assets/proyek/proyek4.png",
    nama: "Agenda Kelas",
    desk: "Website berfungsi untuk memberikan Informasi kegiatan dan agenda selama perkuliahan",
    tools: ["Html", "CSS", "Bootstrap"],
    dad: "500",
    link: "https://github.com/solihunsir/webkelas_rpl21c",
  },
  {
    id: 5,
    gambar: "/assets/proyek/proyek5.png",
    nama: "Private Chess AI",
    desk: "Platform latihan catur interaktif berbasis web dengan analisis taktis real-time secara 100% offline, mengintegrasikan mesin Stockfish 16 (WASM) untuk memberikan evaluasi langkah, riwayat analisis terstruktur",
    tools: ["Next.js", "React.js", "TailwindCSS", "WASM", "Stockfish"],
    dad: "500",
    link: "https://github.com/solihunsir/private-chess-ai",
  },
  {
    id: 6,
    gambar: "/assets/proyek/proyek6.png",
    nama: "Smart Village Ecosystem",
    desk: "Platform ekosistem desa cerdas yang dirancang untuk pengintegrasian laporan desa, marketplace produk lokal/desa, serta wadah interaksi komunitas desa.",
    tools: ["Flutter", "Laravel", "TailwindCSS", "REST API", "SQLite", "GitHub"],
    dad: "600",
    link: "https://github.com/solihunsir/smart-village",
  },
  {
    id: 7,
    gambar: "/assets/proyek/proyek7.png",
    nama: "Monitoring Kendaraan RORO Bengkalis",
    desk: "Sistem mengenai monitoring kendaraan di pelabuhan penyeberangan RORO Bengkalis, meningkatkan transparansi Data dan mempermudah pembuatan Laporan",
    tools: ["Python", "YOLOv8", "FastAPI", "Sqlite3"],
    dad: "700",
    link: "https://github.com/solihunsir/monitoring-roro",
  },
];

export const listAgenda = [
  {
    id: 1,
    gambar: "/assets/agenda/agenda1.png",
    nama: "Juara 1 Catur PKM & Porseni",
    desk: "Pertandingan Catur yang diikuti oleh seluruh Mahasiswa aktif Politeknik Negeri Bengkalis",
    dad: "200",
  },
  {
    id: 2,
    gambar: "/assets/agenda/agenda2.png",
    nama: "Juara 2 Pemrograman Web",
    desk: "Pertandingan yang diikuti oleh seluruh Mahasiswa & Siswa Se-Kabupaten Bengkalis",
    dad: "200",
  },
  {
    id: 3,
    gambar: "/assets/agenda/agenda3.png",
    nama: "Juara 1 Desain Web",
    desk: "Pertandingan Desain Web diikuti oleh Mahasiswa Aktif Jurusan Teknik Informatika",
    dad: "200",
  },
  {
    id: 4,
    gambar: "/assets/agenda/agenda4.png",
    nama: "Juara Mahasiswa Terbaik Catur",
    desk: "Pertandingan Catur Umum yang dikuti Oleh Mahasiswa Aktif Se-Kabupaten Bengkalis",
    dad: "200",
  },
  {
    id: 5,
    gambar: "/assets/agenda/agenda5.png",
    nama: "Juara Video Editing",
    desk: "Pertandingan Video Editing yang diikuti oleh seluruh Mahasiswa Politeknik Negeri Bengkalis",
    dad: "200",
  },
  {
    id: 6,
    gambar: "/assets/agenda/agenda6.png",
    nama: "Sertifikat Front-End & Back-End Developer",
    desk: "Program Coding Camp Powered By DBS Foundation",
    dad: "200",
  },
  {
    id: 7,
    gambar: "/assets/agenda/agenda7.png",
    nama: "Sertifikat Pertukaran Mahasiswa Merdeka",
    desk: "Program Pertukaran Mahasiswa Merdeka Batch 3 di Politeknik Negeri Pontianak",
    dad: "200",
  },
  {
    id: 8,
    gambar: "/assets/agenda/agenda8.png",
    nama: "Sertifikat Web Intermediate",
    desk: "Sertifikat yang didapatkan dari Dicoding dengan kelas Web Intermediate",
    dad: "200",
  },
  {
    id: 9,
    gambar: "/assets/agenda/agenda9.png",
    nama: "Sertifikat Magang Berdampak",
    desk: "Sertifikat Magang Berdampak di PT Citiasia Internasional.",
    dad: "200",
  },
];
